### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by DuhonTheGuy** [itsOwen/discord-blogger-integration#2]
General features to be implemented.

**Comment by itsOwen** [comment]
As you know we can do anything as we have the google blogger API, maybe you can try a auto-notify features whenever something is updated or added to the website, the discord bot will notify everyone

**Comment by itsOwen** [comment]
- Auto Notify When Post Updates on a blogger website. - Status Completed
- Send Notification to the specific roles and everyone - Status Completed
- More features yet to discuss.

**Comment by itsOwen** [comment]
Added Notify when someone updates a post or add something new to blogger blogspot.

**Comment by itsOwen** [comment]
Added Send Notification to the specific roles and everyone.

**Comment by HritamSamanta** [comment]
the code is not working i am writing ++search(then the topic) but its not giving me any result..................help me plz

**Comment by itsOwen** [comment]
> the code is not working i am writing ++search(then the topic) but its not giving me any result..................help me plz

You need to install requirements and add your blogger API and other stuff read steps

**Comment by Aggareth** [comment]
only search is working its not sending update whenever i update something on blogger kindly guide me

**Comment by itsOwen** [comment]
> only search is working its not sending update whenever i update something on blogger kindly guide me ![image](https://user-images.githubusercontent.com/93094643/153702358-2c320bec-fabb-4f5d-a129-e092103255a8.png) bot perms
> 
> ![image](https://user-images.githubusercontent.com/93094643/153702741-6a10bee6-98f1-41be-ba67-761334fd11a4.png)

it might be a permission thing or something as I just tested and it works fine

**Comment by Aggareth** [comment]
@itsOwen can u please gimme ur discord id or add me i need ur help coz i tried everything bot permission, api key etc 
i am still unable to figure it out 
add me please 
crown#7393

**Comment by itsOwen** [comment]
> @itsOwen can u please gimme ur discord id or add me i need ur help coz i tried everything bot permission, api key etc i am still unable to figure it out add me please crown#7393

Issue resolved
